//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitiveAssessmentsC.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CognitiveAssessmentsC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap btn1_1 {
            get {
                object obj = ResourceManager.GetObject("btn1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn1_2 {
            get {
                object obj = ResourceManager.GetObject("btn1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn1_3 {
            get {
                object obj = ResourceManager.GetObject("btn1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn1_4 {
            get {
                object obj = ResourceManager.GetObject("btn1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn1_5 {
            get {
                object obj = ResourceManager.GetObject("btn1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn1_6 {
            get {
                object obj = ResourceManager.GetObject("btn1_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn1_7 {
            get {
                object obj = ResourceManager.GetObject("btn1_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn1_8 {
            get {
                object obj = ResourceManager.GetObject("btn1_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_1 {
            get {
                object obj = ResourceManager.GetObject("btn10_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_2 {
            get {
                object obj = ResourceManager.GetObject("btn10_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_3 {
            get {
                object obj = ResourceManager.GetObject("btn10_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_4 {
            get {
                object obj = ResourceManager.GetObject("btn10_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_5 {
            get {
                object obj = ResourceManager.GetObject("btn10_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_6 {
            get {
                object obj = ResourceManager.GetObject("btn10_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_7 {
            get {
                object obj = ResourceManager.GetObject("btn10_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn10_8 {
            get {
                object obj = ResourceManager.GetObject("btn10_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn2_1 {
            get {
                object obj = ResourceManager.GetObject("btn2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn2_2 {
            get {
                object obj = ResourceManager.GetObject("btn2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn2_3 {
            get {
                object obj = ResourceManager.GetObject("btn2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn2_4 {
            get {
                object obj = ResourceManager.GetObject("btn2_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn2_5 {
            get {
                object obj = ResourceManager.GetObject("btn2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn2_6 {
            get {
                object obj = ResourceManager.GetObject("btn2_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn3_1 {
            get {
                object obj = ResourceManager.GetObject("btn3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn3_2 {
            get {
                object obj = ResourceManager.GetObject("btn3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn3_3 {
            get {
                object obj = ResourceManager.GetObject("btn3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn3_4 {
            get {
                object obj = ResourceManager.GetObject("btn3_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn3_5 {
            get {
                object obj = ResourceManager.GetObject("btn3_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn3_6 {
            get {
                object obj = ResourceManager.GetObject("btn3_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn4_1 {
            get {
                object obj = ResourceManager.GetObject("btn4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn4_2 {
            get {
                object obj = ResourceManager.GetObject("btn4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn4_3 {
            get {
                object obj = ResourceManager.GetObject("btn4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn4_4 {
            get {
                object obj = ResourceManager.GetObject("btn4_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn4_5 {
            get {
                object obj = ResourceManager.GetObject("btn4_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn4_6 {
            get {
                object obj = ResourceManager.GetObject("btn4_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn5_1 {
            get {
                object obj = ResourceManager.GetObject("btn5_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn5_2 {
            get {
                object obj = ResourceManager.GetObject("btn5_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn5_3 {
            get {
                object obj = ResourceManager.GetObject("btn5_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn5_4 {
            get {
                object obj = ResourceManager.GetObject("btn5_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn5_5 {
            get {
                object obj = ResourceManager.GetObject("btn5_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn5_6 {
            get {
                object obj = ResourceManager.GetObject("btn5_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_1 {
            get {
                object obj = ResourceManager.GetObject("btn6_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_2 {
            get {
                object obj = ResourceManager.GetObject("btn6_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_3 {
            get {
                object obj = ResourceManager.GetObject("btn6_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_4 {
            get {
                object obj = ResourceManager.GetObject("btn6_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_5 {
            get {
                object obj = ResourceManager.GetObject("btn6_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_6 {
            get {
                object obj = ResourceManager.GetObject("btn6_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_7 {
            get {
                object obj = ResourceManager.GetObject("btn6_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn6_8 {
            get {
                object obj = ResourceManager.GetObject("btn6_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_1 {
            get {
                object obj = ResourceManager.GetObject("btn7_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_2 {
            get {
                object obj = ResourceManager.GetObject("btn7_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_3 {
            get {
                object obj = ResourceManager.GetObject("btn7_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_4 {
            get {
                object obj = ResourceManager.GetObject("btn7_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_5 {
            get {
                object obj = ResourceManager.GetObject("btn7_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_6 {
            get {
                object obj = ResourceManager.GetObject("btn7_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_7 {
            get {
                object obj = ResourceManager.GetObject("btn7_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn7_8 {
            get {
                object obj = ResourceManager.GetObject("btn7_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_1 {
            get {
                object obj = ResourceManager.GetObject("btn8_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_2 {
            get {
                object obj = ResourceManager.GetObject("btn8_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_3 {
            get {
                object obj = ResourceManager.GetObject("btn8_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_4 {
            get {
                object obj = ResourceManager.GetObject("btn8_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_5 {
            get {
                object obj = ResourceManager.GetObject("btn8_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_6 {
            get {
                object obj = ResourceManager.GetObject("btn8_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_7 {
            get {
                object obj = ResourceManager.GetObject("btn8_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn8_8 {
            get {
                object obj = ResourceManager.GetObject("btn8_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_1 {
            get {
                object obj = ResourceManager.GetObject("btn9_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_2 {
            get {
                object obj = ResourceManager.GetObject("btn9_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_3 {
            get {
                object obj = ResourceManager.GetObject("btn9_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_4 {
            get {
                object obj = ResourceManager.GetObject("btn9_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_5 {
            get {
                object obj = ResourceManager.GetObject("btn9_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_6 {
            get {
                object obj = ResourceManager.GetObject("btn9_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_7 {
            get {
                object obj = ResourceManager.GetObject("btn9_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btn9_8 {
            get {
                object obj = ResourceManager.GetObject("btn9_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_1 {
            get {
                object obj = ResourceManager.GetObject("btnP1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_2 {
            get {
                object obj = ResourceManager.GetObject("btnP1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_3 {
            get {
                object obj = ResourceManager.GetObject("btnP1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_4 {
            get {
                object obj = ResourceManager.GetObject("btnP1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_5 {
            get {
                object obj = ResourceManager.GetObject("btnP1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_6 {
            get {
                object obj = ResourceManager.GetObject("btnP1_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_7 {
            get {
                object obj = ResourceManager.GetObject("btnP1_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP1_8 {
            get {
                object obj = ResourceManager.GetObject("btnP1_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_1 {
            get {
                object obj = ResourceManager.GetObject("btnP2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_2 {
            get {
                object obj = ResourceManager.GetObject("btnP2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_3 {
            get {
                object obj = ResourceManager.GetObject("btnP2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_4 {
            get {
                object obj = ResourceManager.GetObject("btnP2_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_5 {
            get {
                object obj = ResourceManager.GetObject("btnP2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_6 {
            get {
                object obj = ResourceManager.GetObject("btnP2_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_7 {
            get {
                object obj = ResourceManager.GetObject("btnP2_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnP2_8 {
            get {
                object obj = ResourceManager.GetObject("btnP2_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel1 {
            get {
                object obj = ResourceManager.GetObject("panel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel10 {
            get {
                object obj = ResourceManager.GetObject("panel10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel2 {
            get {
                object obj = ResourceManager.GetObject("panel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel3 {
            get {
                object obj = ResourceManager.GetObject("panel3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel4 {
            get {
                object obj = ResourceManager.GetObject("panel4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel5 {
            get {
                object obj = ResourceManager.GetObject("panel5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel6 {
            get {
                object obj = ResourceManager.GetObject("panel6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel7 {
            get {
                object obj = ResourceManager.GetObject("panel7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel8 {
            get {
                object obj = ResourceManager.GetObject("panel8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panel9 {
            get {
                object obj = ResourceManager.GetObject("panel9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panelP1 {
            get {
                object obj = ResourceManager.GetObject("panelP1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap panelP2 {
            get {
                object obj = ResourceManager.GetObject("panelP2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
